version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: healthcare-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - healthcare-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: healthcare-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - healthcare-network

volumes:
  redis_data:

networks:
  healthcare-network:
    driver: bridge
